# Running GROMACS on AQE for Polymer Simulation

This notebook will demonstrate the pipeline of calculating glass transition temperature $(T_g)$ using GROMACS molecular dynamics software.

- [x] We need to load an AiiDA profile. The `load_profile` method will load the default profile if no explicit profile name is specified.

In [1]:
from aiida import load_profile
load_profile()

Profile<uuid='854b62c634cd4cd6ade4c630f3c0af0e' name='gromacs'>

#Delete this shell. (No USE -- )
%aiida
%verdi status

We need to set some user defined parameters which will be used throughout the pipeline

In [2]:
# Polymer/Monomer inputs
monomer_pdbfilename = '14tPBMonomer.pdb'        # PDB filename of the monomer
monomer_count_per_polymer = 4                   # Number of monomers present in one polymer
# polymer_pdbfilename = '14tPBSingleChain.pdb'    # PDB filename of the polymer
# polymer_count = 50                              # Number of polymer in the simulation box

# MD simulation inputs
thermo_T = 300.15                               # Simulation Temperature (K)
thermo_P = 1.0                                  # Simulation Pressure (bar)

Two types of input data is required from the user.
1. Polymer input/Monomoer input - User will provide the name of the polymer and the number of polymers they want to use in molecular dynamics simulation inorder to optimize the computational cost with highest efficacy.
(**_NOTE:_** Once the polymerization step is introduced, the polymer input will be replaced by the monomer inputs.)

2. MD simulation inputs - User will provide an absolute thermodynamic condition for the simulation (i.e. temperature and pressure) or a range of temperature and pressure at which simulation will be conducted.

**_NOTE 1:_** A minimum intervention will be required after this.

**_NOTE 2: Currently the PoC is for linear homopolymer._**

Necessary python packages are imported.

In [3]:
import pathlib
import os
import numpy as np

from aiida import engine, orm
from aiida_shell import launch_shell_job

Convert the user input into `aiida.orm` `Data` types accepted by the `node` arguments. 

- [ ] Polymerization step

In [4]:
monomer_pdbfilename = orm.Str(monomer_pdbfilename)
monomer_count_per_polymer = orm.Int(monomer_count_per_polymer)

#polymer_pdbfilename = orm.Str(polymer_pdbfilename)
#polymer_count = orm.Int(polymer_count)

thermo_T = orm.Float(thermo_T)
thermo_P = orm.Float(thermo_P)

In [5]:
print(monomer_pdbfilename)

uuid: 644aba7b-46e9-4595-ab7d-61e5c5a65eca (unstored) value: 14tPBMonomer.pdb


In [6]:
monomer = orm.SinglefileData(os.getcwd() + '/' + monomer_pdbfilename.value)
lines = monomer.get_content().split('\n')
monomer_atom_lines = [line for line in lines if line.startswith('ATOM') or line.startswith('HETATM')]

In [7]:
class Atom:
    def __init__(self, num: int = -1, line: str = ''):
        if num >= 0:
            self.atom_number = num
            self.atom_name = line[12:16].split()[0]
            self.residue_name = line[17:20].split()[0]
            self.residue_seq_num = int(line[22:26].split()[0])
            self.coord = [float(line[30:38].split()[0]), \
                          float(line[38:46].split()[0]), \
                          float(line[46:54].split()[0])]
            self.element = line[76:78].split()[0]
        else:
            self.atom_number = num
            self.atom_name = ''
            self.residue_name = ''
            self.residue_seq_num = num
            self.coord = [float(num), \
                          float(num), \
                          float(num)]
            self.element = ''
    def set_atom_number(self, num: int):
        self.atom_number = num
    def set_atom_name(self, name: str):
        self.atom_name = name
    def set_residue_name(self, name: str):
        self.residue_name = name
    def set_residue_seq_num(self, num: int):
        self.residue_seq_num = num
    def set_coord(self, coord: list):
        self.coord = coord
    def set_element(self, element: str):
        self.element = element
    def set_everything(self, atom_number: int, atom_name: str, residue_name: str, residue_seq_num: int, coord: list, element: str):
        self.set_atom_number(atom_number)
        self.set_atom_name(atom_name)
        self.set_residue_name(residue_name)
        self.set_residue_seq_num(residue_seq_num)
        self.set_coord(coord)
        self.set_element(element)
    def get_pdb_str(self):
        pdb_str = "ATOM  %5d %-4s %3s  %4d    %8.3f%8.3f%8.3f                      %2s" \
        % (self.atom_number+1, self.atom_name, self.residue_name, self.residue_seq_num+1, float(self.coord[0]), float(self.coord[1]), float(self.coord[2]), self.element)
        return pdb_str
    def as_dict(self) -> dict:
        return {'atom_number': self.atom_number, 'atom_name': self.atom_name, \
                'residue_name': self.residue_name, 'residue_seq_num': self.residue_seq_num, \
                'coord': self.coord, 'element': self.element}

In [8]:
monomer_all_atom_list = orm.List()
for i, atom_line in enumerate(monomer_atom_lines):
    monomer_all_atom_list.append(orm.JsonableData(Atom(i, atom_line)))

In [18]:
@engine.calcfunction
def get_unit_vector(p1: orm.ArrayData, p2: orm.ArrayData) -> orm.ArrayData:

    vec = p1.get_array() - p2.get_array()
    vec /= np.linalg.norm(vec)

    return orm.ArrayData(vec)

@engine.calcfunction
def get_rotation_matrix(vec1: orm.ArrayData, vec2: orm.ArrayData) -> orm.ArrayData:

    # Calculate the angle between vec1 and vec2 and rotation angle to align vec2 to vec1
    dot_product = np.dot(vec1.get_array(), vec2.get_array())
    rotation_angle = np.arccos(dot_product)
    print('rangle = ', rotation_angle)

    cos_angle = np.cos(rotation_angle)
    sin_angle = np.sin(rotation_angle)
    
    # Calculate the rotation axis (cross product)
    rotation_axis = np.cross(vec1.get_array(), vec2.get_array())
    rotation_axis /= np.linalg.norm(rotation_axis)

    rotation_matrix = np.array([
        [cos_angle + rotation_axis[0] * rotation_axis[0] * (1 - cos_angle), \
        rotation_axis[0] * rotation_axis[1] * (1 - cos_angle) - rotation_axis[2] * sin_angle, \
        rotation_axis[0] * rotation_axis[2] * (1 - cos_angle) + rotation_axis[1] * sin_angle],
        [rotation_axis[1] * rotation_axis[0] * (1 - cos_angle) + rotation_axis[2] * sin_angle, \
        cos_angle + rotation_axis[1] * rotation_axis[1] * (1 - cos_angle), \
        rotation_axis[1] * rotation_axis[2] * (1 - cos_angle) - rotation_axis[0] * sin_angle],
        [rotation_axis[2] * rotation_axis[0] * (1 - cos_angle) - rotation_axis[1] * sin_angle, \
        rotation_axis[2] * rotation_axis[1] * (1 - cos_angle) + rotation_axis[0] * sin_angle, 
        cos_angle + rotation_axis[2] * rotation_axis[2] * (1 - cos_angle)]
    ])
    return orm.ArrayData(rotation_matrix)

@engine.calcfunction
def rotate_coord(atom_coord: orm.ArrayData, ref_coord: orm.ArrayData, rotation_matrix: orm.ArrayData) -> orm.ArrayData:

    ref_atom_vec = atom_coord.get_array() - ref_coord.get_array()
    
    rotated_coord_vec = np.dot(rotation_matrix.get_array(), ref_atom_vec)
    new_atom_coord = ref_coord.get_array() + rotated_coord_vec

    return orm.ArrayData(new_atom_coord)

In [25]:
polymer_all_atom_list = orm.List()
polymer_remove_atom_index_list = orm.List()

In [26]:
# Add monomers to the polymer chain
polymer_atom_count = 0
for imonomer in range(monomer_count_per_polymer.value):
    monomer_atom_count = len(monomer_all_atom_list)
    # first monomer
    if imonomer == 0:
        for iatom in monomer_all_atom_list:
            curratom = Atom()
            curratom.set_everything(iatom.obj.atom_number, iatom.obj.atom_name, \
                                    iatom.obj.residue_name, iatom.obj.residue_seq_num, \
                                   iatom.obj.coord, iatom.obj.element)
            polymer_all_atom_list.append(orm.JsonableData(curratom))
            polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_number = polymer_atom_count
            polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.residue_seq_num = imonomer
            if iatom.obj.atom_name == 'HW3':
                polymer_remove_atom_index_list.append(polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_number)
            polymer_atom_count += 1
        print(imonomer, 'Done')
    else:
        # get the CW of last monomer
        cw_index = -1
        for iatom in polymer_all_atom_list:
            if iatom.obj.atom_name == 'CW':
                cw_index = iatom.obj.atom_number

        if cw_index < 0:
            raise ValueError('CW atom is not found.')
        
        # get the HA3 of model monomer
        ha3_index = -1
        for iatom in monomer_all_atom_list:
            if iatom.obj.atom_name == 'HA3':
                ha3_index = iatom.obj.atom_number
                
        if ha3_index < 0:
            raise ValueError('HA3 atom is not found.')

        dtranslate = np.array(polymer_all_atom_list[cw_index].obj.coord) \
        - np.array(monomer_all_atom_list[ha3_index].obj.coord)
                    
        # put the next monomer in the polymer + translation
        for iatom in monomer_all_atom_list:
            curratom = Atom()
            curratom.set_everything(iatom.obj.atom_number, iatom.obj.atom_name, \
                                    iatom.obj.residue_name, iatom.obj.residue_seq_num, \
                                   iatom.obj.coord, iatom.obj.element)
            polymer_all_atom_list.append(orm.JsonableData(curratom))
            polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_number = polymer_atom_count
            polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.residue_seq_num = imonomer
            coord = np.array(polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.coord) + dtranslate
            polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.coord = coord.tolist()
            
            if polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_name == 'HA3':
                polymer_remove_atom_index_list.append(polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_number)
            elif polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_name == 'HW3':
                if polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.residue_seq_num != monomer_count_per_polymer.value - 1:
                    polymer_remove_atom_index_list.append(polymer_all_atom_list[len(polymer_all_atom_list)-1].obj.atom_number)
            polymer_atom_count += 1

        #for iatom in polymer_all_atom_list:
        #    print(iatom.obj.get_pdb_str())

        # rotation starts here
        # CW.coord == HA3.coord
        # get the CA of last monomer
        ca_index = -1
        for iatom in polymer_all_atom_list:
            if iatom.obj.atom_name == 'CA':
                ca_index = iatom.obj.atom_number
                
        if ca_index < 0:
            raise ValueError('CA atom is not found.')

        # get the HW3 of previous monomer
        hw3_index = -1
        for iatom in polymer_all_atom_list:
            if iatom.obj.atom_name == 'HW3' and iatom.obj.residue_seq_num == imonomer - 1:
                hw3_index = iatom.obj.atom_number
                
        if hw3_index < 0:
            raise ValueError('HW3 atom is not found.')

        #print('CW', cw_index, 'CA', ca_index, 'HW3', hw3_index)
        
        cw_hw3_unit_vec = get_unit_vector(orm.ArrayData(np.array(polymer_all_atom_list[hw3_index].obj.coord)), \
                              orm.ArrayData(np.array(polymer_all_atom_list[cw_index].obj.coord)))

        cw_ca_unit_vec = get_unit_vector(orm.ArrayData(np.array(polymer_all_atom_list[ca_index].obj.coord)), \
                              orm.ArrayData(np.array(polymer_all_atom_list[cw_index].obj.coord)))

        #print(cw_hw3_unit_vec.get_array(), cw_ca_unit_vec.get_array())

        rotation_matrix = get_rotation_matrix(cw_hw3_unit_vec, cw_ca_unit_vec)

        print('rotation matrix ->')
        print(rotation_matrix.get_array())

        #print('rotated coordinate ->')
        for iatom in polymer_all_atom_list:
            if iatom.obj.residue_seq_num == imonomer and iatom.obj.atom_name != '':
                iatom.obj.coord = rotate_coord(orm.ArrayData(np.array(iatom.obj.coord)), \
                                               orm.ArrayData(np.array(polymer_all_atom_list[ca_index].obj.coord)), \
                                              rotation_matrix).get_array().tolist()
            #print(iatom.obj.get_pdb_str())
        print(imonomer, 'Done')
for iatom in polymer_all_atom_list:
    print(iatom.obj.get_pdb_str())
print('remove ->', polymer_remove_atom_index_list.get_list())

0 Done
rotation matrix ->
[[ 0.96693046  0.02430379 -0.25387952]
 [-0.01883453  0.99953568  0.02395162]
 [ 0.25434376 -0.01837785  0.96693925]]
1 Done
rotation matrix ->
[[ 0.86992409 -0.03094551  0.49221383]
 [ 0.05245834  0.99817365 -0.02995807]
 [-0.49038781  0.05188196  0.86995866]]
2 Done
rotation matrix ->
[[ 0.96693046  0.02430379 -0.25387952]
 [-0.01883453  0.99953568  0.02395162]
 [ 0.25434376 -0.01837785  0.96693925]]
3 Done
ATOM      1 CA   BD1     1       8.280  51.200  30.550                       C
ATOM      2 HA1  BD1     1       8.790  50.330  30.140                       H
ATOM      3 HA2  BD1     1       8.830  52.120  30.380                       H
ATOM      4 HA3  BD1     1       8.380  51.100  31.630                       H
ATOM      5 CB   BD1     1       6.890  51.370  30.050                       C
ATOM      6 HB   BD1     1       6.230  50.510  30.130                       H
ATOM      7 CG   BD1     1       6.460  52.520  29.510                       C
ATOM    

In [29]:
lines = [iatom.obj.get_pdb_str() for iatom in polymer_all_atom_list if iatom.obj.atom_number not in polymer_remove_atom_index_list.get_list()]
polymer = orm.SinglefileData.from_string('\n'.join(lines), filename='14tPBMonomer4mer.pdb')

In [110]:
'''               NOTE                  '''
# For all the polymerization we will attach
# CW of current monomer with CA of the next monomer
# For start of the polymer look for CA
# For end of the polymer look for CW
'''                END                  '''
# Get all coordinates
atom_lines = []
for atom_line in monomer_atom_lines:
    atom_lines.append([float(atom_line[30:38].split()[0]), float(atom_line[38:46].split()[0]), float(atom_line[46:54].split()[0])])
monomer_atom_coords = orm.ArrayData(np.array(atom_lines))
del atom_lines

# Locate start of a polymer
begin_monomer_atom_line = [line for line in monomer_atom_lines if 'CA' in line]
print('CA ', begin_monomer_atom_line)
begin_monomer_atom_coord = orm.ArrayData(np.array([float(begin_monomer_atom_line[0][30:38].split()[0]), float(begin_monomer_atom_line[0][38:46].split()[0]), float(begin_monomer_atom_line[0][46:54].split()[0])]))
print(begin_monomer_atom_coord.get_array())

# Locate start connecting point of a polymer
begin_connection_atom_line = [line for line in monomer_atom_lines if 'HA3' in line]
print('HA3 ', begin_connection_atom_line)
begin_connection_atom_coord = orm.ArrayData(np.array([float(begin_connection_atom_line[0][30:38].split()[0]), float(begin_connection_atom_line[0][38:46].split()[0]), float(begin_connection_atom_line[0][46:54].split()[0])]))
print(begin_connection_atom_coord.get_array())

# Locate end of a polymer
end_monomer_atom_line = [line for line in monomer_atom_lines if 'CW' in line]
print('CW ', end_monomer_atom_line)
end_monomer_atom_coord = orm.ArrayData(np.array([float(end_monomer_atom_line[0][30:38].split()[0]), float(end_monomer_atom_line[0][38:46].split()[0]), float(end_monomer_atom_line[0][46:54].split()[0])]))
print(end_monomer_atom_coord.get_array())

# Locate end connecting point of a polymer
end_connection_atom_line = [line for line in monomer_atom_lines if 'HW3' in line]
print('HW3 ', end_connection_atom_line)
end_connection_atom_coord = orm.ArrayData(np.array([float(end_connection_atom_line[0][30:38].split()[0]), float(end_connection_atom_line[0][38:46].split()[0]), float(end_connection_atom_line[0][46:54].split()[0])]))
print(end_connection_atom_coord.get_array())

@engine.calcfunction
def get_monomer_backbone_vector(cx1: orm.ArrayData, cx2: orm.ArrayData) -> orm.ArrayData:
    vec = cx1.get_array() - cx2.get_array()
    magnitude = np.linalg.norm(vec)
    unit_vec = vec / magnitude

    return orm.ArrayData(unit_vec)

# Get backbone vector of a monomer
monomer_backbone_unitvec = get_monomer_backbone_vector(begin_monomer_atom_coord, end_monomer_atom_coord)
print(monomer_backbone_unitvec.get_array())

[ 0.81681757 -0.38201929  0.43228499]


We are opening the file and wrap it in AiiDA's `SinglefileData` data type, which allows it to be stored in the provenance graph.

In [5]:
polymer = orm.SinglefileData(os.getcwd() + '/' + polymer_pdbfilename.value)

The `gmx pdb2gmx` is the first GROMACS command to create th topology file according to the forcefield information for the polymer.

In [6]:
@engine.calcfunction
def calc_molecular_weight_polymer(polymer: orm.SinglefileData) -> orm.Float:
    import pandas as pd
    elecsvfile = os.getcwd() + '/elements.csv'
    dataframe_elements = pd.read_csv(elecsvfile, index_col = None)
    
    lines = polymer.get_content().split('\n')
    atom_lines = [line for line in lines if line.startswith('ATOM') or line.startswith('HETATM')]

    # Calculate molecular weight
    molecular_weight_polymer = 0.0
    for line in atom_lines:
        # Find element and atomic mass from the periodic table
        elestr = line[12:14]

        if elestr[0] == ' ':
            if elestr[1].isalpha() and elestr[1].isupper():
                ele = elestr[1]
            else:
                ele = ' '
        elif elestr[0].isdigit():
            if elestr[1].isalpha() and elestr[1].isupper():
                ele = elestr[1]
            else:
                ele = ' '
        elif elestr[0].isalpha() and elestr[0].isupper():
            if elestr[1].isdigit():
                ele = elestr[0]
            else:
                ele = elestr
        else:
            ele = ' '

        try:
            molecular_weight_polymer += float(dataframe_elements.loc[dataframe_elements['Symbol'] == ele, 'AtomicMass'].iloc[0])
        except:
            raise Exception(f'ERROR: Atom type of {elestr} not found.')

    return orm.Float(molecular_weight_polymer)

@engine.calcfunction
def calc_simulation_box_length(molecular_weight_polymer: orm.Float, polymer_count: orm.Int) -> orm.Float:
    molecular_weight = molecular_weight_polymer.value * polymer_count.value
    
    # Default density (0.4 g/cm3)
    density = 0.4
    avogadro_number = 6.022e23  # molecules/mol
    cm_to_nm = 1e7  # cm to nm conversion factor
    
    # Step 1: Mass of one molecule
    mass_per_molecule = molecular_weight / avogadro_number  # g
    
    # Step 2: Volume of cubic box
    volume = mass_per_molecule / density  # cm³
    
    # Step 3: Side length of the cubic box
    box_length = volume**(1/3)  # cm
    box_length = box_length * cm_to_nm  # nm

    return orm.Float(box_length)

molecular_weight_polymer = calc_molecular_weight_polymer(polymer)
box_length = calc_simulation_box_length(molecular_weight_polymer, polymer_count)

We are setting the force-field folder and wrap it in AiiDA's `FolderData` data type, which allows it to be stored in the provenance graph.

In [7]:
# Default Parameters
ffdir = os.getcwd() + '/oplsaa.ff'
oplsaa = orm.FolderData(tree=ffdir)                       

In [8]:
# Run `gmx pdb2gmx` to convert the PDB to GROMACS .gro format.
results_pdb2gmx, node_pdb2gmx = launch_shell_job(
    'gmx',
    arguments='pdb2gmx -f {polymer} -o polymer_out.pdb -water spce -ff oplsaa',
    nodes={
        'polymer': polymer,
        'folder': oplsaa,
    },
    filenames={
        'folder': 'oplsaa.ff'
    },
    outputs=['polymer_out.pdb', 'topol.top', 'posre.itp'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_pdb2gmx['stdout'].get_content())

                  :-) GROMACS - gmx pdb2gmx, 2023.3-spack (-:

Executable:   /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2/bin/gmx_mpi
Data prefix:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2
Working dir:  /anfhome/aamir/scratch/aiida/9f/84/13d6-b178-4e10-b9ff-e3dde09d4563
Command line:
  gmx_mpi pdb2gmx -f 14tPBSingleChain.pdb -o polymer_out.pdb -water spce -ff oplsaa

Force field 'oplsaa' occurs in 2 places. pdb2gmx is using the one in the current directory. Use interactive selection (not the -ff option) if you would prefer a different one.
Force field 'oplsaa' occurs in 2 places. pdb2gmx is using the one in the current directory. Use interactive selection (n

<div class="alert alert-info">
`gmx` is the GROMACS executable which will be executed with several parameters. The `nodes` argument takes a dictionary of `SinglefileData` and `FolderData` which will be copied to the working directory where the `gmx` command is executed. The `oplsaa` in `nodes` are copied to the `oplsaa.ff` folder in the working directory. If the key of the node appears as a placeholder in the `arguments` argument, it is replaced with its filename. 
</div>

The `gmx pdb2gmx` is expected to generate three outputs of interest:
- `polymer_out.pdb`: `.pdb` file of the polymer.
- `topol.top`: The topology file.
- `posre.itp`: The position restraint file included in the topology file.

<div class="alert alert-info">
These output files will be used in the upcoming steps in the pipeline. To capture these output files in the AiiDA's provenance graph, these filenames are declared in the `output` argunent. `aiida-shell` will wrap these output files in a `SinglefileDtata`.
</div>

Similar to the previous steps, GROMACS creates a simulation box where mutiple chains of the polymer will be inserted for the MD simulations. From the previous step, `.pdb` file of the single polymer chain is used to replicate the polymer chain inside the simulation box. In the output, we get a simulation box containing `polymer_count` number of polymers.

In [9]:
@engine.calcfunction
def check_insert_molecules(log: orm.SinglefileData, polymer_count: orm.Int) -> orm.Bool:
    lines = log.get_content().split('\n')
    check_lines = [line for line in lines if line.startswith('Added')]
    
    if len(check_lines) > 1:
        raise Exception('ERROR: Multiple lines got selected in the check_lines variable', check_lines)

    wordlist = check_lines[0].split()
    polymer_count_inserted = orm.Int(wordlist[1])
    
    if polymer_count_inserted.value == polymer_count.value:
        return orm.Bool(False)
    else:
        return orm.Bool(True)

run = orm.Bool(True)
while run.value:
    results_insert, node_insert = launch_shell_job(
        'gmx',
        arguments='insert-molecules -box {box_length} -ci {polymer} -nmol {polymer_count} -try 999 -o melt.pdb',
        nodes={
            'box_length': box_length,
            'polymer': polymer,
            'polymer_count': polymer_count,
        },
        outputs=['melt.pdb'],
        metadata={'options': {'redirect_stderr': True}},
    )
    #print(results_insert['stdout'].get_content())
    run = check_insert_molecules(results_insert['stdout'], polymer_count)
    print(run.value)
    if run.value:
        
        run = orm.Bool(False)
    else:
        run = orm.Bool(False)
    print(run.value)

              :-) GROMACS - gmx insert-molecules, 2023.3-spack (-:

Executable:   /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2/bin/gmx_mpi
Data prefix:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2
Working dir:  /anfhome/aamir/scratch/aiida/7a/df/b074-d007-46bc-a700-8a1390ea2fdb
Command line:
  gmx_mpi insert-molecules -box 8.2514028455544 -ci 14tPBSingleChain.pdb -nmol 50 -try 999 -o melt.pdb

Initialising inter-atomic distances...

         based on residue and atom names, since they could not be
         definitively assigned from the information in your input
         files. These guessed numbers might deviate from the mass
         and radius of the atom ty

While running the `pdb2gmx` command we have created the topology for one single polymer chain. However, in the `topol.top` file we have to provide the number of polymer chain present in the simulation box. Therefore, we are updating the number of molecules line from 1 to `polymer_count` using the `sed` command.

In [10]:
results_updatetop, node_updatetop = launch_shell_job(
    'sed',
    arguments='-i "s/Other               1/Other               23/g" {top}',
    nodes={
        'top': results_pdb2gmx['topol_top'],
    },
    outputs=['topol.top'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_updatetop['stdout'].get_content())

<div class="alert alert-info">
The output `topol.top` file is declared in the `output` argunent where `aiida-shell` will wrap these output files in a `SinglefileDtata`.
</div>

**Prerequisite for MD simulations and simulation box preparation is completed and we can proceed to run the molecular dynamics simulation.**

In [11]:
em_mdp = orm.SinglefileData.from_string(
    """
    integrator      = steep
    emtol           = 1000.0
    emstep          = 0.01
    nsteps          = 50000
    nstlist         = 1
    cutoff-scheme   = Verlet
    ns_type         = grid
    coulombtype     = PME
    rcoulomb        = 1.0
    rvdw            = 1.0
    pbc             = xyz
    ld_seed         = 1
    gen_seed        = 1
    """,
    filename='em.mdp',
)

# Run `gmx grompp` to pre-process the parameters for energy minimization.
results_grompp_em, node_grompp_em = launch_shell_job(
    'gmx',
    arguments='grompp -f {mdp} -c {gro} -p {top} -o output.tpr',
    nodes={
        'mdp': em_mdp,
        'gro': results_insert['melt_pdb'],
        'top': results_updatetop['topol_top'],
        'folder': oplsaa,
    },
    filenames={
        'folder': 'oplsaa.ff'
    },
    outputs=['output.tpr'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_grompp_em['stdout'].get_content())

The `gmx grompp` takes the input of three necesary files to generate the `.tpr` file.
- [x] `.mdp`: The molecular dynamics parameters.
- [x] `.gro`: The coordinate information of all the polymer chains present in the simulation box.
- [x] `.top`: The tolology file of the polymer. Also, this has the information of number of polymers present in the simulation box.

The generated `.tpr` file is used for running the molecular dynamics simulation. We can run the `gmx mdrun` to run the energy minimization step.

In [12]:
# Run `gmx mdrun` to run the energy minimization.
results_em, node_em = launch_shell_job(
    'gmx',
    arguments='mdrun -v -deffnm output -s {tpr}',
    nodes={
        'tpr': results_grompp_em['output_tpr'],
    },
    outputs=['output.edr', 'output.gro', 'output.log'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_em['stdout'].get_content())

                   :-) GROMACS - gmx mdrun, 2023.3-spack (-:

Executable:   /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2/bin/gmx_mpi
Data prefix:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2
Working dir:  /anfhome/aamir/scratch/aiida/01/6e/5946-56d5-4125-93f8-bf1c22da8889
Command line:
  gmx_mpi mdrun -v -deffnm output -s output.tpr

Reading file output.tpr, VERSION 2023.3-spack (single precision)
Using 1 MPI process

Non-default thread affinity set, disabling internal thread affinity

Using 8 OpenMP threads 


Steepest Descents:
   Tolerance (Fmax)   =  1.00000e+03
   Number of steps    =        50000
Step=    0, Dmax= 1.0e-02 nm, Epot=  2.45157e+04 Fmax= 1.37

Similar to the previous `gmx grompp` step, we can proceed with NPT equilibration step where the molecular dynamics simulation will be performed at the given thermodynamic conditions given by the user.

In [13]:
eqnpt_mdp = orm.SinglefileData.from_string(
    """
    title                   = NPT Equilibration
    ;define                 = -DPOSRES
    integrator              = md
    dt                      = 0.002
    nsteps                  = 50000
    nstenergy               = 2000
    nstxout-compressed      = 10000
    nstvout                 = 0
    nstlog                  = 1000
    gen_vel                 = yes
    gen_temp                = 298.15
    pbc                     = xyz
    cutoff-scheme           = Verlet
    rlist                   = 1.0
    ns_type                 = grid
    nstlist                 = 10
    coulombtype             = PME
    fourierspacing          = 0.12
    pme_order               = 4
    rcoulomb                = 1.0
    vdwtype                 = Cut-Off
    rvdw                    = 1.0
    DispCorr                = EnerPres
    constraints             = h-bonds
    constraint_algorithm    = lincs
    lincs_iter              = 1
    lincs_order             = 4
    tcoupl                  = v-rescale
    tc-grps                 = System
    ref_t                   = 298.15
    tau_t                   = 0.1
    pcoupl                  = c-rescale
    pcoupltype              = isotropic
    ref_p                   = 1.0
    tau_p                   = 2.0
    ;refcoord-scaling        = com
    compressibility         = 4.5e-5
    """,
    filename='eqnpt.mdp',
)

# Run `gmx grompp` to pre-process the parameters for energy minimization.
results_grompp_eqnpt, node_grompp_eqnpt = launch_shell_job(
    'gmx',
    arguments='grompp -f {mdp} -c {gro} -p {top} -o npt.tpr',
    nodes={
        'mdp': eqnpt_mdp,
        'gro': results_em['output_gro'],
        'top': results_updatetop['topol_top'],
        'folder': oplsaa,
    },
    filenames={
        'folder': 'oplsaa.ff'
    },
    outputs=['npt.tpr'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_grompp_eqnpt['stdout'].get_content())

                   :-) GROMACS - gmx grompp, 2023.3-spack (-:

Executable:   /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2/bin/gmx_mpi
Data prefix:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-zen3/aocc-4.1.0/gromacs-2023.3-upt5rsow4zsttzs63kqercg7her4e3e2
Working dir:  /anfhome/aamir/scratch/aiida/f2/3c/3948-9c6d-42b8-91dc-1c8b8c4afd25
Command line:
  gmx_mpi grompp -f eqnpt.mdp -c output.gro -p topol.top -o npt.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'ns_type'
Setting the LD random seed to -604112979

Generated 362526 of the 362526 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 0.5

Generated 362526 of the 362526 1-4 parameter combinations

Excluding 3 bonded neighbours 

The generated `.tpr` file is used for running the molecular dynamics simulation for NPT equilibration. We can run the `gmx mdrun` to run the NPT equilibration step.

In [14]:
# Run `gmx mdrun` to run the energy minimization.
results_eqnpt, node_eqnpt = launch_shell_job(
    'gmx',
    arguments='mdrun -v -deffnm output -s {tpr}',
    nodes={
        'tpr': results_grompp_eqnpt['npt_tpr'],
    },
    outputs=['output.edr', 'output.gro', 'output.log', 'output.xtc'],
    metadata={'options': {'redirect_stderr': True}},
)
#print(results_eqnpt['stdout'].get_content())

**MD simulation is completed. Therefore, we can go for analysis of the simulated system.**

<div class="alert alert-info">
Using `gmx energy` command we can calculate and plot the primary properties for the simulated polymer system.
</div>

In [15]:
# Run `gmx energy` to extract the potential energy during the energy minimization.
results_energy, node_energy = launch_shell_job(
    'gmx',
    arguments='energy -f {edr} -o potential.xvg',
    nodes={
        'edr': results_eqnpt['output_edr'],
        'stdin': orm.SinglefileData.from_string('10\n0'),
    },
    outputs=['potential.xvg'],
    metadata={'options': {'redirect_stderr': True, 'filename_stdin': 'stdin'}},
)

<div class="alert alert-info">
The input for `gmx energy` is the `output.edr` from the `results_eqnpt`. Here we first pass `10` which corresponds to the potential energy, followed by `0` which finalizes the selection and completes the prompt. The `output` file of this step saved as GROMACS generated `.xvg` format.
</div>

To visualize the data, first we need to import necessary python packages to be installed.

In [16]:
import io

import matplotlib.pyplot as plt
import numpy as np

from IPython.display import display, IFrame

We define the `create_plot` function and pass the `potential.xvg` from the previous step. The `create_plot` will create a plot which is saved to a stream in memory which is then passed to a `SinglefileData` node to store it in AiiDA's provecance graph.

In [17]:
@engine.calcfunction
def create_plot(xvg: orm.SinglefileData) -> orm.SinglefileData:
    """Plot the data of a XVG output file."""
    lines = xvg.get_content().split('\n')
    data = np.loadtxt(lines, comments=['#', '@']).T
    plt.figure(figsize=(6,4))
    plt.plot(*data)
    plt.xlabel('Time (ps)')
    plt.ylabel('Potential energy [kJ/mol]')
    stream = io.BytesIO()
    plt.savefig(stream, format='png', bbox_inches='tight', dpi=150)
    #stream.seek(0)
    return orm.SinglefileData(stream, filename='potential.png')
    
# Create a plot from the extracted potential energy of the system
plot = create_plot(results_energy['potential_xvg'])

In the same way we can get the density data from the `output.edr` using the `gmx energy` command and plot it.

In [18]:
# Run `gmx energy` to extract the potential energy during the energy minimization.
results_energy, node_energy = launch_shell_job(
    'gmx',
    arguments='energy -f {edr} -o density.xvg',
    nodes={
        'edr': results_eqnpt['output_edr'],
        'stdin': orm.SinglefileData.from_string('22\n0'),
    },
    outputs=['density.xvg'],
    metadata={'options': {'redirect_stderr': True, 'filename_stdin': 'stdin'}},
)

In [19]:
@engine.calcfunction
def create_plot(xvg: orm.SinglefileData) -> orm.SinglefileData:
    """Plot the data of a XVG output file."""
    lines = xvg.get_content().split('\n')
    data = np.loadtxt(lines, comments=['#', '@']).T
    plt.plot(*data)
    plt.xlabel('Time (ps)')
    plt.ylabel('Density $[kg/m^3]$')
    stream = io.BytesIO()
    plt.savefig(stream, format='png', bbox_inches='tight', dpi=300)
    #stream.seek(0)
    return orm.SinglefileData(stream, filename='density.png')

# Create a plot from the extracted density of the system
plot = create_plot(results_energy['density_xvg'])

300.15


In [38]:
thermo_T_count = 5
thermo_T_list = orm.ArrayData(np.array([thermo_T.value-10.0, thermo_T.value-5.0]))

In [39]:
from aiida.engine.daemon.client import get_daemon_client

client = get_daemon_client()
client.start_daemon()

In [40]:
@engine.calcfunction
def set_mdp_parameter(id: int=0, thermo_T: np.float64=298.15, thermo_P: np.float64=1.0, ) -> orm.SinglefileData:
    mdp_str = f"""
    title                   = NPT Equilibration
    ;define                 = -DPOSRES
    integrator              = md
    dt                      = 0.002
    nsteps                  = 50000
    nstenergy               = 2000
    nstxout-compressed      = 10000
    nstvout                 = 0
    nstlog                  = 1000
    gen_vel                 = yes
    gen_temp                = 298.15
    pbc                     = xyz
    cutoff-scheme           = Verlet
    rlist                   = 1.0
    ns_type                 = grid
    nstlist                 = 10
    coulombtype             = PME
    fourierspacing          = 0.12
    pme_order               = 4
    rcoulomb                = 1.0
    vdwtype                 = Cut-Off
    rvdw                    = 1.0
    DispCorr                = EnerPres
    constraints             = h-bonds
    constraint_algorithm    = lincs
    lincs_iter              = 1
    lincs_order             = 4
    tcoupl                  = v-rescale
    tc-grps                 = System
    ref_t                   = {thermo_T.value}
    tau_t                   = 0.1
    pcoupl                  = c-rescale
    pcoupltype              = isotropic
    ref_p                   = {thermo_P.value}
    tau_p                   = 2.0
    ;refcoord-scaling        = com
    compressibility         = 4.5e-5
    """

    #print(mdp_str)
    #print('T = ', thermo_T.value)
    #print('P = ', thermo_P.value)

    return orm.SinglefileData.from_string(mdp_str, filename=f'eqnpt-{id.value}.mdp')

nodelist = []
resultslist = []

for i, thermo_T_ele in enumerate(thermo_T_list.get_array()):
    print(i, thermo_T_ele, type(thermo_T_ele), type(i))
    eqnpt_mdp = set_mdp_parameter(i, thermo_T_ele, thermo_P)
    print(eqnpt_mdp.filename)
    #print(eqnpt_mdp.get_content())

    print(i)
    tpr = f'npt-{i}.tpr'
    results_grompp_eqnpt, node_grompp_eqnpt = launch_shell_job(
        'gmx',
        arguments='grompp -f {mdp} -c {gro} -p {top} -o {tpr}',
        nodes={
            'mdp': eqnpt_mdp,
            'gro': results_em['output_gro'],
            'top': results_updatetop['topol_top'],
            'tpr': orm.Str(tpr),
            'folder': oplsaa,
        },
        filenames={
            'folder': 'oplsaa.ff'
        },
        outputs=[tpr],
        metadata={'options': {'redirect_stderr': True}},
    )
    nodelist.append(node_grompp_eqnpt)
    resultslist.append(results_grompp_eqnpt)
    #print(node_grompp_eqnpt.outputs.stdout.get_content())
    print('done')

0 290.15 <class 'numpy.float64'> <class 'int'>
eqnpt-0.mdp
0
done
1 295.15 <class 'numpy.float64'> <class 'int'>
eqnpt-1.mdp
1
done


In [41]:
print(nodelist)

[<CalcJobNode: uuid: 32603611-d2b0-4ffa-9323-967db18d2c90 (pk: 4152) (aiida.calculations:core.shell)>, <CalcJobNode: uuid: 09aa274d-4f72-4794-be7d-701ecb8cee63 (pk: 4165) (aiida.calculations:core.shell)>]


In [42]:
print(resultslist)

[{'npt_0_tpr': <SinglefileData: uuid: 4d22018d-3dad-435f-90ec-052092796a34 (pk: 4155)>, 'stdout': <SinglefileData: uuid: 02a1740b-9287-45af-a231-b3db5135c2ee (pk: 4156)>}, {'npt_1_tpr': <SinglefileData: uuid: 6a505202-9e9a-4060-bb10-84c07f20480a (pk: 4168)>, 'stdout': <SinglefileData: uuid: 059df435-7a17-461e-9705-fa1fef59f56c (pk: 4169)>}]


In [43]:
for i, result in enumerate(resultslist):
    ou = f'npt_{i}_tpr'
    print(type(result[ou]))

<class 'aiida.orm.nodes.data.singlefile.SinglefileData'>
<class 'aiida.orm.nodes.data.singlefile.SinglefileData'>


In [44]:
node_dumplist = []
results_dumplist = []

for i, thermo_T_ele in enumerate(thermo_T_list.get_array()):
    print(i, thermo_T_ele, type(thermo_T_ele), type(i))
    tpr = f'npt_{i}_tpr'
    dump = f'npt-{i}.dump'
    print(tpr)
    results_dump, node_dump = launch_shell_job(
        'gmx',
        arguments='dump -s {tpr}',
        nodes={
            'tpr': resultslist[i][tpr],
        },
        metadata={'options': {'redirect_stderr': True}},
    )
    node_dumplist.append(node_dump)
    results_dumplist.append(results_dump)
    print('done')

0 290.15 <class 'numpy.float64'> <class 'int'>
npt_0_tpr
done
1 295.15 <class 'numpy.float64'> <class 'int'>
npt_1_tpr
done


In [45]:
#print(results_dumplist[0]['stdout'].get_content())

In [58]:
import aiida_aqe

In [59]:
import aiida_aqe.tools

In [64]:
dir(aiida_aqe.tools)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']